apiVersion: v1
kind: Service
metadata:
  name: dara-vite-file-d4c9f-service
spec:
  type: NodePort
  selector:
    app: dara-vite-file-d4c9f
  ports:
    - protocol: TCP
      port: 8198
      targetPort: 5173
